swagger: "2.0"
info:
  version: "1.0.0"
  title: Saving Grace API
# during dev, should point to your local machine
host: localhost:4000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /empresa:
    # binds a127 app logic to a route
    x-swagger-router-controller: empresa
    get:
      description: Retorna uma ou mais Empresas
      # used as the method name of the controller
      operationId: empresa
      parameters:
        - name: id
          in: query
          description: Filtra o retorno por id
          required: false
          type: number
        - name: from
          in: query
          description: Define o inicio do intervalo de linhas a ser retornado
          required: false
          type: number
        - name: to
          in: query
          description: Define o fim do intervalo de linhas a ser retornado
          required: false
          type: number
        - name: orderBy
          in: query
          description: Define o nome da propriedade que será utilizada para ordenar
          required: false
          type: string
        - name: orderType
          in: query
          description: Define o método de ordenação
          required: false
          type: string
        - name: usuario
          in: query
          description: Define se o usuário deve ser incluido no retorno
          required: false
          type: boolean
        - name: avaliacao
          in: query
          description: Define se as avaliações devem ser incluidas no retorno
          required: false
          type: boolean
        - name: premio
          in: query
          description: Define se os prêmios devem ser incluidos no retorno
          required: false
          type: boolean
        - name: transacao
          in: query
          description: Define se as transações devem ser incluidas no retorno
          required: false
          type: boolean
        - name: comentario
          in: query
          description: Define se os comentários devem ser incluidos no retorno
          required: false
          type: boolean
      responses:
        "default":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
